version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    # ↓ここが重要！あなたのパッケージ自体をインストールして
    # docstringを読めるようにします
    - method: pip
      path: .

mkdocs:
  configuration: mkdocs.yml